name: "CI: check linting and build images"

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master", "main"]

  push:
    branches: ["master", "main"]

  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  linter:
    environment: local
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/local.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  builder-unstable:
    environment: production
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Build movix-admin:unstable Docker image
        uses: docker/build-push-action@v2
        with:
          file: "./compose/production/django/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/stranded-in-python/movix-admin:unstable
          labels: |
            maintainer=${{ github.actor }}
            build-date=${{ github.event.head_commit.timestamp }}

      - name: Build movix-admin:dev Docker image
        uses: docker/build-push-action@v2
        with:
          file: "./compose/local/django/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/stranded-in-python/movix-admin:dev
          labels: |
            maintainer=${{ github.actor }}
            build-date=${{ github.event.head_commit.timestamp }}

      - name: Build movix-s2p:unstable Docker image
        uses: docker/build-push-action@v2
        with:
          file: "./compose/production/sqlite_to_postgres/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/stranded-in-python/movix-s2p:unstable
          labels: |
            maintainer=${{ github.actor }}
            build-date=${{ github.event.head_commit.timestamp }}
